// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMNUoSm_Gu-Fg6AnNPzQBzXoFlqwnzQiE',
    appId: '1:1092198467867:web:64fe4afac04eeb3506ebbe',
    messagingSenderId: '1092198467867',
    projectId: 'tokenmanagementapp',
    authDomain: 'tokenmanagementapp.firebaseapp.com',
    storageBucket: 'tokenmanagementapp.firebasestorage.app',
    measurementId: 'G-2B18RB1XVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzV7LR6ZEQON7ghC_R7-1Hj4zj7BwlkSg',
    appId: '1:1092198467867:android:ae95779badffa7b106ebbe',
    messagingSenderId: '1092198467867',
    projectId: 'tokenmanagementapp',
    storageBucket: 'tokenmanagementapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGPC04NJ3GUYgObw177_Gh8W5zm-vDzmc',
    appId: '1:1092198467867:ios:9127989f13f1a44e06ebbe',
    messagingSenderId: '1092198467867',
    projectId: 'tokenmanagementapp',
    storageBucket: 'tokenmanagementapp.firebasestorage.app',
    iosBundleId: 'com.example.tokenManagementUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGPC04NJ3GUYgObw177_Gh8W5zm-vDzmc',
    appId: '1:1092198467867:ios:9127989f13f1a44e06ebbe',
    messagingSenderId: '1092198467867',
    projectId: 'tokenmanagementapp',
    storageBucket: 'tokenmanagementapp.firebasestorage.app',
    iosBundleId: 'com.example.tokenManagementUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMNUoSm_Gu-Fg6AnNPzQBzXoFlqwnzQiE',
    appId: '1:1092198467867:web:ba95329ccc7ebba406ebbe',
    messagingSenderId: '1092198467867',
    projectId: 'tokenmanagementapp',
    authDomain: 'tokenmanagementapp.firebaseapp.com',
    storageBucket: 'tokenmanagementapp.firebasestorage.app',
    measurementId: 'G-N047MJ9GP4',
  );

}